#ddev-generated
# If you remove the ddev-generated line above you
# are responsible for maintaining this file. DDEV will not then
# update it, for example if you add `additional_hostnames`, etc.

http:
  routers:
    webshop-pgm-zegerschaeverbeke-xhgui-80-http:
      entrypoints:
        - http-8143
      rule: HostRegexp(`^webshop-pgm-zegerschaeverbeke\.ddev\.site$`)
      
      service: "webshop-pgm-zegerschaeverbeke-xhgui-80"
      ruleSyntax: v3
      tls: false
      # middlewares:
      #   - "webshop-pgm-zegerschaeverbeke-redirectHttps"
    webshop-pgm-zegerschaeverbeke-web-80-http:
      entrypoints:
        - http-80
      rule: HostRegexp(`^webshop-pgm-zegerschaeverbeke\.ddev\.site$`)
      
      service: "webshop-pgm-zegerschaeverbeke-web-80"
      ruleSyntax: v3
      tls: false
      # middlewares:
      #   - "webshop-pgm-zegerschaeverbeke-redirectHttps"
    webshop-pgm-zegerschaeverbeke-web-8025-http:
      entrypoints:
        - http-8025
      rule: HostRegexp(`^webshop-pgm-zegerschaeverbeke\.ddev\.site$`)
      
      service: "webshop-pgm-zegerschaeverbeke-web-8025"
      ruleSyntax: v3
      tls: false
      # middlewares:
      #   - "webshop-pgm-zegerschaeverbeke-redirectHttps"
    
    
    webshop-pgm-zegerschaeverbeke-xhgui-80-https:
      entrypoints:
        - http-8142
      rule: HostRegexp(`^webshop-pgm-zegerschaeverbeke\.ddev\.site$`)
      
      service: "webshop-pgm-zegerschaeverbeke-xhgui-80"
      ruleSyntax: v3
      
      tls: true
      
    
    
    webshop-pgm-zegerschaeverbeke-web-80-https:
      entrypoints:
        - http-443
      rule: HostRegexp(`^webshop-pgm-zegerschaeverbeke\.ddev\.site$`)
      
      service: "webshop-pgm-zegerschaeverbeke-web-80"
      ruleSyntax: v3
      
      tls: true
      
    webshop-pgm-zegerschaeverbeke-web-8025-https:
      entrypoints:
        - http-8026
      rule: HostRegexp(`^webshop-pgm-zegerschaeverbeke\.ddev\.site$`)
      
      service: "webshop-pgm-zegerschaeverbeke-web-8025"
      ruleSyntax: v3
      
      tls: true
      
    

  middlewares:
    webshop-pgm-zegerschaeverbeke-redirectHttps:
      redirectScheme:
        scheme: https
        permanent: true

  services:
    webshop-pgm-zegerschaeverbeke-xhgui-80:
      loadbalancer:
        servers:
          - url: http://ddev-webshop-pgm-zegerschaeverbeke-xhgui:80
        
    
    webshop-pgm-zegerschaeverbeke-web-80:
      loadbalancer:
        servers:
          - url: http://ddev-webshop-pgm-zegerschaeverbeke-web:80
        
    webshop-pgm-zegerschaeverbeke-web-8025:
      loadbalancer:
        servers:
          - url: http://ddev-webshop-pgm-zegerschaeverbeke-web:8025
        
    
    
    

tls:
  certificates:
    - certFile: /mnt/ddev-global-cache/traefik/certs/webshop-pgm-zegerschaeverbeke.crt
      keyFile: /mnt/ddev-global-cache/traefik/certs/webshop-pgm-zegerschaeverbeke.key